### ISSUE TITLE
shadcn or Tailwind styling not working

### ISSUE THREAD

**Issue by jaydrennan** [dansholds/astro-shadcn-starter#1]
Both setting up your project and my own I've failed to get the styling working for a simple component like a button. Any suggestions?
 
 I'm new to astro and shadcn so it's possible I'm doing something silly.

**Comment by dansholds** [comment]
Hey Jay, sorry for the late response, I'll have a look but it should work out of the box with an `npm i` & `npm run dev`

**Comment by dansholds** [comment]
I'm going to assume this is a none issue for you now and close, feel free to reopen
